### ISSUE TITLE
Can't find projects

### ISSUE THREAD

**Issue by christianmagill** [bchatard/phpstorm-alfred-workflow#1]
I get "Can't find projects: check configuration or contact developer" installing for the first time on the latest EAP.

I've followed Requirements and Installation and even checked the files mentioned in the Customization section and everything looks good.

Thanks

**Comment by bchatard** [comment]
Hi,
Sorry I did not see the notification for this issue... I'll check that asap.

**Comment by bchatard** [comment]
@christianmagill you need to download the new package version

**Comment by christianmagill** [comment]
Awesome! Works great, much thanks!
