### ISSUE TITLE
Getting no command line luncher when I do have it

### ISSUE THREAD

**Issue by ilyador** [bchatard/phpstorm-alfred-workflow#5]
Trying to use it with WebStorm 11.0.3, I have `/usr/local/bin/wstorm` but still getting error in Alfred that it is not found.

**Comment by bchatard** [comment]
Hi,

Try this workflow [https://github.com/bchatard/jetbrains-alfred-workflow](https://github.com/bchatard/jetbrains-alfred-workflow). It works with all Jetbrains products.

**Comment by ilyador** [comment]
Yes, this is what I am using. I thought I opened the issue there, only now I noticed in in PhpStorm workflow..

**Comment by bchatard** [comment]
@ilyador ok
can you open the issue in the other projet please and add some details about the error. Thanks
