### ISSUE TITLE
some of my projects cannot be found

### ISSUE THREAD

**Issue by jyj1993126** [bchatard/phpstorm-alfred-workflow#6]
I really like this plugin,
but some of my projects cannot be found ,
How does this search for my projects ?

**Comment by bchatard** [comment]
Hi,

How many projects did you have when you hit your keyword?
PhpStorm save a _limited_ list of projects.

**Comment by christianmagill** [comment]
I'm having the same issue.

I recently moved some projects around with a new development setup. Only one project out of three shows up. I have tried to remove the recentProjectDirectories.xml file, and it gets regenerated as I start opening projects in PHPStorm, however the Workflow is not keeping pace and still only shows the same original project.

Any ideas?

Thanks for the workflow! I use it often.

**Comment by bchatard** [comment]
Hi @christianmagill,

Can you provide more details about your environnement?
- OSX version
- PhpStorm version
  - Sed version (in Terminal: `sed --version`)

Also, try to regenerate command line tools.

Thanks,

**Comment by christianmagill** [comment]
OSX 10.11.6
PhpStorm 2016.2.1
Build #PS-162.1628.23, built on August 10, 2016

sed command outputs illegal option

I have tried regenerating command line tools and does not fix issue.

Thanks,

**Comment by bchatard** [comment]
@christianmagill 
this workflow is for older PhpStorm version, please use the new one: [Jetbrains Alfred Workflow](https://github.com/bchatard/jetbrains-alfred-workflow)

**Comment by christianmagill** [comment]
Thanks,

That did the trick!

**Comment by bchatard** [comment]
:-)
